### PR TITLE
Allowing deploy from prime url

### PR DESCRIPTION
**Pull request by tnovau**
Allowing this urls too. When using github is needed to use deploy previews link that netlify provides to you.

`DEPLOY_PRIME_URL`: This URL represents the primary URL for an individual deploy, or a group of them, like branch deploys and Deploy Previews; for example, `https://feature-branch--petsof.netlify.app` or `https://deploy-preview-1--petsof.netlify.app`

[Docs](https://docs.netlify.com/configure-builds/environment-variables/#deploy-urls-and-metadata)

### CODE REVIEW

**Comment by romainbessugesmeusy** [comment]
Hey, why did you close it?

**Comment by tnovau** [comment]
Just need a few fixes for duplicated urls, will reopen today

**Comment by tnovau** [comment]
Done :heavy_check_mark: 

Please review if it is ok now :+1:

**Comment by romainbessugesmeusy** [comment]
Hmm I noticed I used my GATBSY_AUTH0_CLIENTID env variable and think it's too specific. I'm gonna rename it `AUTH0_CLIENT_ID`.

**Comment by tnovau** [comment]
Good idea, I'm using react is weird to have that name

**Comment by romainbessugesmeusy** [comment]
1.1.0 is published (minor instead of patch because of ENV variable renaming)

**Pull request merged**
